image: haskell:9.4.5
tasks:
  - name: Init
    init: stack config set install-ghc false && stack config set system-ghc true &&
      stack build --only-dependencies --test
vscode:
  extensions:
    - MS-vsliveshare.vsliveshare
