image: docker.io/sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.9.2_3.3.0
tasks:
  - name: Init
    init: ""
vscode:
  extensions:
    - MS-vsliveshare.vsliveshare
    - scalameta.metals
    - scala-lang.scala
